---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bill-splitter.fullname" . }}-backend
  labels:
    app: backend
    instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
      instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: backend
        instance: {{ .Release.Name }}
    spec:
      containers:
        - name: backend
          image: "ghcr.io/{{ .Values.image.owner }}/bill-splitter-backend:IMAGE_TAG_PLACEHOLDER_BACKEND"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backend.env.secretName }}
                  key: {{ .Values.backend.env.secretKey }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bill-splitter.fullname" . }}-frontend
  labels:
    app: frontend
    instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
      instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: frontend
        instance: {{ .Release.Name }}
    spec:
      containers:
        - name: frontend
          image: "ghcr.io/{{ .Values.image.owner }}/bill-splitter-frontend:IMAGE_TAG_PLACEHOLDER_FRONTEND"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
