 {{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bill-splitter.fullname" . }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /scan-receipt
            pathType: Prefix
            backend:
              service:
                name: {{ include "bill-splitter.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /sync
            pathType: Prefix
            backend:
              service:
                name: {{ include "bill-splitter.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /share/batch-check
            pathType: Prefix
            backend:
              service:
                name: {{ include "bill-splitter.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /share
            pathType: Prefix
            backend:
              service:
                name: {{ include "bill-splitter.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /onetime-key
            pathType: Prefix
            backend:
              service:
                name: {{ include "bill-splitter.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /create-checkout-session
            pathType: Prefix
            backend:
              service:
                name: {{ include "bill-splitter.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /verify-session
            pathType: Prefix
            backend:
              service:
                name: {{ include "bill-splitter.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /create-customer-portal-session
            pathType: Prefix
            backend:
              service:
                name: {{ include "bill-splitter.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "bill-splitter.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}