 {{- if .Values.secret.create -}}
{{- if or (not .Values.secret.API_KEY) }}
{{- fail "When secret.create is true, the value for API_KEY must be provided." -}}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bill-splitter.fullname" . }}-secret
type: Opaque
data:
  API_KEY: {{ .Values.secret.API_KEY | b64enc | quote }}
  # Stripe secrets - encode even if empty strings
  STRIPE_SECRET_KEY: {{ .Values.secret.STRIPE_SECRET_KEY | b64enc | quote }}
  STRIPE_PRICE_ID_MONTHLY: {{ .Values.secret.STRIPE_PRICE_ID_MONTHLY | b64enc | quote }}
  STRIPE_PRICE_ID_YEARLY: {{ .Values.secret.STRIPE_PRICE_ID_YEARLY | b64enc | quote }}
  # PayPal secrets - encode even if empty strings
  PAYPAL_CLIENT_ID: {{ .Values.secret.PAYPAL_CLIENT_ID | b64enc | quote }}
  PAYPAL_CLIENT_SECRET: {{ .Values.secret.PAYPAL_CLIENT_SECRET | b64enc | quote }}
  PAYPAL_PLAN_ID_MONTHLY: {{ .Values.secret.PAYPAL_PLAN_ID_MONTHLY | b64enc | quote }}
  PAYPAL_PLAN_ID_YEARLY: {{ .Values.secret.PAYPAL_PLAN_ID_YEARLY | b64enc | quote }}
{{- end }}