{{- if .Values.secret.create -}}
{{- if or (not .Values.secret.API_KEY) (not .Values.secret.STRIPE_SECRET_KEY) (not .Values.secret.STRIPE_PRICE_ID_MONTHLY) (not .Values.secret.STRIPE_PRICE_ID_YEARLY) }}
{{- fail "When secret.create is true, values for API_KEY and all STRIPE_* variables must be provided." -}}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bill-splitter.fullname" . }}-secret
type: Opaque
data:
  API_KEY: {{ .Values.secret.API_KEY | b64enc | quote }}
  STRIPE_SECRET_KEY: {{ .Values.secret.STRIPE_SECRET_KEY | b64enc | quote }}
  STRIPE_PRICE_ID_MONTHLY: {{ .Values.secret.STRIPE_PRICE_ID_MONTHLY | b64enc | quote }}
  STRIPE_PRICE_ID_YEARLY: {{ .Values.secret.STRIPE_PRICE_ID_YEARLY | b64enc | quote }}
{{- end -}}