---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bill-splitter.fullname" . }}-backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: backend
    instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bill-splitter.fullname" . }}-frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: frontend
    instance: {{ .Release.Name }}
