name: Run Tests

on:
  workflow_dispatch:
    inputs:
      branch_to_test:
        description: 'The branch to check out and test'
        required: true
        type: string

jobs:
  test:
    name: Run Vitest Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_to_test }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
