name: 5. Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'The tag for the Docker images (e.g., commit SHA)'
        required: true
  workflow_call:
    inputs:
      image_tag:
        description: 'The tag for the Docker images (e.g., commit SHA)'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}
  FRONTEND_IMAGE_NAME: bill-splitter-frontend
  BACKEND_IMAGE_NAME: bill-splitter-backend

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: dist

      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-dist
          path: backend-dist

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.frontend.yaml
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ inputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.backend.yaml
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.BACKEND_IMAGE_NAME }}:${{ inputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
