name: Utility - Get AWS Lambda URL

on:
  workflow_call:
    outputs:
      function_url:
        description: "The deployed AWS Lambda Function URL."
        value: ${{ jobs.get_url.outputs.function_url }}

env:
  AWS_REGION: us-east-1
  LAMBDA_FUNCTION_NAME: SharedBills-Backend

jobs:
  get_url:
    name: Get Lambda Function URL
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: read
    outputs:
      function_url: ${{ steps.lambda_url.outputs.FUNCTION_URL }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubAction-Lambda-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Lambda Function URL
        id: lambda_url
        run: |
          URL_CONFIG=$(aws lambda get-function-url-config --function-name ${{ env.LAMBDA_FUNCTION_NAME }} --query 'FunctionUrl' --output text 2>/dev/null || echo "")
          if [ -z "$URL_CONFIG" ]; then
            echo "Lambda Function URL for '${{ env.LAMBDA_FUNCTION_NAME }}' not found."
            echo "FUNCTION_URL=" >> $GITHUB_OUTPUT
          else
            echo "Found Lambda Function URL: ${URL_CONFIG}"
            echo "FUNCTION_URL=${URL_CONFIG}" >> $GITHUB_OUTPUT
          fi
