name: 10. Main Orchestrator

on:
  workflow_dispatch:

jobs:
  get_tag:
    name: Generate Image Tag
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}
    steps:
      - name: Extract Docker metadata for tag
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: type=sha,prefix=,format=short

  build_backend:
    name: Build Backend
    uses: ./.github/workflows/01-build-backend.yaml
    secrets: inherit

  deploy_lambda:
    name: Deploy AWS Lambda
    needs: build_backend
    uses: ./.github/workflows/02-deploy-aws.yaml
    secrets: inherit

  build_frontend:
    name: Build Frontend
    needs: deploy_lambda
    uses: ./.github/workflows/03-build-frontend.yaml
    with:
      api_urls: "https://k.sharedbills.app,${{ needs.deploy_lambda.outputs.function_url }}"
    secrets: inherit

  publish_artifacts:
    name: Publish to Branches
    if: success()
    needs: [build_backend, build_frontend]
    uses: ./.github/workflows/04-publish-to-branches.yaml
    secrets: inherit

  build_docker_images:
    name: Build Docker Images
    needs: [get_tag, build_backend, build_frontend]
    uses: ./.github/workflows/05-build-docker.yaml
    with:
      image_tag: ${{ needs.get_tag.outputs.image_tag }}
    secrets: inherit
  
  update_helm_chart:
    name: Update Helm Chart
    needs: [get_tag, build_docker_images]
    uses: ./.github/workflows/06-update-helm.yaml
    with:
      image_tag: ${{ needs.get_tag.outputs.image_tag }}
    secrets: inherit

