# Default values for bill-splitter chart.
# This file contains the default configuration for a PRODUCTION deployment.
# For development, you can create a `values.dev.yaml` file and use it
# with `helm install/upgrade -f values.dev.yaml`.
# ---

image:
  owner: PLACEHOLDER_OWNER

frontend:
  enabled: true # Set to false if you are hosting the frontend on a CDN (e.g., Cloudflare Pages, Vercel)
  replicaCount: 2
  service:
    port: 80

backend:
  replicaCount: 1
  service:
    port: 3000
  cors:
    # IMPORTANT: Set this to the full origin of your frontend application.
    # For example: https://your-frontend-domain.com
    allowedOrigin: "https://your-frontend-domain.com"
  # The payment provider to use. Can be 'stripe' or 'paypal'. Defaults to 'paypal'.
  paymentProvider: "paypal"

# Configuration for secrets
# Set to true to create a new secret from the values below.
# If false, you must ensure a secret with the correct name and keys exists.
secret:
  create: true
  
  # The Gemini API Key. MUST be provided if secret.create is true.
  API_KEY: ""
  
  # --- Stripe Configuration (used if paymentProvider is 'stripe') ---
  STRIPE_SECRET_KEY: ""
  STRIPE_PRICE_ID_MONTHLY: ""
  STRIPE_PRICE_ID_YEARLY: ""
  
  # --- PayPal Configuration (used if paymentProvider is 'paypal') ---
  PAYPAL_CLIENT_ID: ""
  PAYPAL_CLIENT_SECRET: ""
  PAYPAL_PLAN_ID_MONTHLY: ""
  PAYPAL_PLAN_ID_YEARLY: ""


ingress:
  enabled: true
  host: YOUR_DOMAIN_HERE # <-- IMPORTANT: Replace with your domain
  # The subdomain prefix for the backend service. For example, "k" will result in the backend being hosted at "k.YOUR_DOMAIN_HERE".
  # Set to "" (empty string) to disable subdomain routing and serve the backend via paths on the main host.
  backendSubdomainPrefix: "k"
  # tls:
  #   - secretName: sharedbills-tls-secret
  #     hosts:
  #       - YOUR_DOMAIN_HERE

# Redis subchart configuration
# See https://github.com/bitnami/charts/tree/main/bitnami/redis for all available options
redis:
  enabled: true
  auth:
    enabled: false # Keep it simple for now, no password
  master:
    persistence:
      enabled: false # Data is ephemeral, no persistence needed
  replica:
    replicaCount: 0 # We don't need replicas for this use case