name: 1. Build Backend

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build Backend Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Get lockfile from package-lock branch
        run: |
          git fetch origin package-lock --depth=1
          git checkout origin/package-lock -- package-lock.json
          if [ ! -f "package-lock.json" ]; then
            echo "::error::package-lock.json not found on package-lock branch."
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies from lockfile
        run: npm ci

      - name: Build backend application
        run: npm run build:backend

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: |
            dist-server
            package.json
            package-lock.json
