name: 21. Cleanup AWS Lambda Function

on:
  workflow_dispatch:
  workflow_call:

env:
  AWS_REGION: us-east-1
  LAMBDA_FUNCTION_NAME: SharedBills-Backend

jobs:
  cleanup:
    name: Destroy AWS Lambda Function
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubAction-Lambda-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Delete Lambda Function URL
        run: |
          echo "Checking for Lambda Function URL..."
          if aws lambda get-function-url-config --function-name ${{ env.LAMBDA_FUNCTION_NAME }} > /dev/null 2>&1; then
            echo "Deleting Lambda Function URL for ${{ env.LAMBDA_FUNCTION_NAME }}..."
            aws lambda delete-function-url-config --function-name ${{ env.LAMBDA_FUNCTION_NAME }}
            echo "Lambda Function URL deleted."
          else
            echo "Lambda Function URL does not exist. Skipping."
          fi

      - name: Delete Lambda Function
        run: |
          echo "Checking for Lambda function..."
          if aws lambda get-function --function-name ${{ env.LAMBDA_FUNCTION_NAME }} > /dev/null 2>&1; then
            echo "Deleting Lambda function: ${{ env.LAMBDA_FUNCTION_NAME }}..."
            aws lambda delete-function --function-name ${{ env.LAMBDA_FUNCTION_NAME }}
            echo "Lambda function deleted."
          else
            echo "Lambda function does not exist. Skipping."
          fi
      
      - name: Log Cleanup Completion
        run: echo "✅ Lambda function cleanup complete!"
