name: Generate CI/CD Branch and Trigger Lint

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  generate-branch:
    name: Generate ci-cd Branch & Trigger Lint
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update ci-cd branch
        run: |
          set -e

          # Configure git
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # Create a new orphan branch in a temporary directory to ensure a clean state
          TEMP_DIR=$(mktemp -d)
          echo "Working in temporary directory $TEMP_DIR"
          cd "$TEMP_DIR"
          
          # Initialize a new repo and connect to the remote using the PAT
          git init
          git remote add origin "https://x-access-token:${{ secrets.WORKFLOWS_TOKEN }}@github.com/${{ github.repository }}.git"
          
          # Fetch only the main branch to get the cicd files
          git fetch --depth 1 origin main
          
          # Checkout ONLY the 'cicd' directory from the main branch into our empty repo
          git checkout origin/main -- cicd

          # Reorganize files for the new branch structure
          if [ -d "cicd/github/workflows" ]; then
            mv cicd/github .github
          fi
          
          echo "Workflow files prepared:"
          ls -R .github || echo "No workflow files to prepare."

          # Explicitly add only the .github directory to the commit
          if [ -d ".github" ]; then
            git add .github
            git commit -m "chore: Sync CI/CD workflows from main branch [ci skip]"
          else
            # If no files were found, create an empty commit to ensure the branch is created/reset
            git commit --allow-empty -m "chore: Sync CI/CD workflows from main branch [ci skip]"
          fi

          echo "Pushing to ci-cd branch..."
          git push -f origin HEAD:ci-cd
          
          echo "Successfully updated the 'ci-cd' branch with the latest workflows."

      - name: Trigger lint workflow
        run: |
          echo "CI/CD branch updated. Triggering lint workflow to check the main branch..."
          # Wait a moment for the push to ci-cd to settle before triggering
          sleep 5
          gh workflow run 00-lint.yaml --ref ci-cd -f branch_to_lint=${{ github.ref_name }} --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
