name: CI/CD Control Center

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      task:
        description: 'Select a task to run'
        type: choice
        required: true
        default: 'sync-and-lint'
        options:
          - 'sync-and-lint'
          - 'run: 00-lint.yaml'
          - 'run: 10-orchestrator-full.yaml'
          - 'run: 10-deploy-backend-lambda.yaml'
          - 'run: 10-frontend-deploy.yaml'
          - 'run: 10-kubernetes-build.yaml'
          - 'run: 20-redeploy-lambda.yaml'
          - 'run: 21-cleanup-lambda.yaml'
          - 'run: 22-cleanup-docker-images.yaml'
          - 'run: generate-lockfile.yaml'

permissions:
  contents: write
  actions: write

jobs:
  main:
    name: CI/CD Task
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a remote workflow
        if: startsWith(inputs.task, 'run:')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          echo "### Syncing ci-cd branch ###"
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          TEMP_DIR=$(mktemp -d)
          cd "$TEMP_DIR"
          git init
          git remote add origin "https://x-access-token:${WORKFLOWS_TOKEN}@github.com/${{ github.repository }}.git"
          git fetch --depth 1 origin main
          git checkout origin/main -- cicd
          # Extract workflow name, removing the 'run: ' prefix
          WORKFLOW_NAME=$(echo "${{ inputs.task }}" | cut -d' ' -f2)
          echo "Manually triggering '$WORKFLOW_NAME' on the 'ci-cd' branch..."

          if [ "$WORKFLOW_NAME" = "00-lint.yaml" ]; then
            # The lint workflow requires the branch_to_lint input
            gh workflow run "$WORKFLOW_NAME" --ref ci-cd -f branch_to_lint=${{ github.ref_name }} --repo ${{ github.repository }}
          else
            # Other workflows do not take inputs
            gh workflow run "$WORKFLOW_NAME" --ref ci-cd --repo ${{ github.repository }}
          fi

      - name: Sync ci-cd branch and/or trigger lint
        # This runs on push OR on manual trigger if 'sync-and-lint' is selected
        if: github.event_name == 'push' || inputs.task == 'sync-and-lint'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOWS_TOKEN: ${{ secrets.WORKFLOWS_TOKEN }}
        run: |
          set -e
          # --- Step 1: Create or Update ci-cd branch ---
          echo "### Syncing ci-cd branch ###"
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          TEMP_DIR=$(mktemp -d)
          cd "$TEMP_DIR"
          git init
          git remote add origin "https://x-access-token:${WORKFLOWS_TOKEN}@github.com/${{ github.repository }}.git"
          git fetch --depth 1 origin main
          git checkout origin/main -- cicd
          if [ -d "cicd/github/workflows" ]; then
            mkdir -p .github
            mv cicd/github/workflows .github/
          fi
          echo "Workflow files prepared for ci-cd branch:"
          ls -R .github || echo "No workflow files to prepare."
          if [ -d ".github" ]; then
            git add .github
            git commit -m "chore: Sync CI/CD workflows from main branch [ci skip]"
          else
            git commit --allow-empty -m "chore: Sync CI/CD workflows from main branch [ci skip]"
          fi
          echo "Pushing to ci-cd branch..."
          git push -f origin HEAD:ci-cd
          echo "Successfully updated the 'ci-cd' branch."

          # --- Step 2: Trigger lint workflow (only on push) ---
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "### Triggering lint workflow for main branch ###"
            sleep 5 # Wait a moment for the push to settle
            gh workflow run 00-lint.yaml --ref ci-cd -f branch_to_lint=${{ github.ref_name }} --repo ${{ github.repository }}
          else
            echo "Manual sync complete. Skipping automatic lint trigger."
          fi
